name: Spring Boot with Gradle CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    #build 이름 설정 (빌드 체크위해서 설정함)
    name : build
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: build
        
    - name: Make zip file 
      run: zip -r ./$GITHUB_SHA.zip . 
      shell: bash 
      
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1 
      with: 
        aws-access-key-id: ${{SECRETS.AWS_ACCESS_KEY_ID}} 
        aws-secret-access-key: ${{SECRETS.AWS_SECRET_ACCESS_KEY}}
        aws-region: ap-northeast-2 
        
      # S3로 업로드
    - name: Upload to AWS S3
      run: aws s3 cp --region ap-northeast-2 --acl private ./naegahama-build.zip s3://minkicicdbucket/hippo/hippo-build.zip

# Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
        --application-name springboot-intro \
        --deployment-group-name springboot-intro-deploy-group \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=minkicicdbucket,bundleType=zip,key=hippo/hippo-build.zip \
        --region ap-northeast-2
