name: Java CI with Gradle

on: # Event
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs: 
  test: # Job id
    runs-on: ubuntu-latest # Runner
    steps:
    - uses: actions/checkout@v2 # Step
    - name: Set up JDK 1.8 
      uses: actions/setup-java@v1
      with:
        java-version: 1.8 
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
